#!/usr/bin/env bash
# Configure the domain zone:
# www --> 914-lb-01 3.83.192.251
# web-01 --> 914-web-01 18.205.38.219
# web-02 --> 914-web-02 34.138.16.188

# Define subdomains to be evaluated
subdomains_all=("www" "lb-01" "web-01" "web-02")

# Function to perform DNS query and display information
runDig() {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

# Check the number of command-line arguments
if [ $# -eq 1 ]; then
    domain="$1"
    # Iterate over predefined subdomains and display information
    for i in "${subdomains_all[@]}"; do
        runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    # Display information for the specified subdomain
    runDig "$subdomain" "$domain"
fi
