#!/usr/bin/env bash
# Installing nginx on our webserver

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration

sudo nginx -t

sudo service nginx restart
